### ISSUE TITLE
Question about position and event

### ISSUE THREAD

**Issue by ilionic** [matthewshirley/react-midi-hook#4]
Hey, nice library! 
Was looking for some alternatives to https://github.com/djipco/webmidi with hooks support. 
Only question about `position`. 

What's the reasoning to subtract 21 in context of midi spec? 

```
      // Real keyboard notes are different to MIDI notes
      const position = note - 21;
```

Another question about event: 
When single key is pressed getting 4 events: 
(one pressedKey) - "NOTE_OFF" and "NOTE_ON"
(after released, empty pressed key) - "NOTE_ON" and "NOTE_OFF" 
Is it a bug?

**Comment by matthewshirley** [comment]
Hey @ilionic,

Good question. MIDI has 127 bytes (notes) and a piano only has 88 notes. The lowest key on the piano is MIDI note 21. In my testing, I wanted to know the "real" key that was pressed on the device.

In regards to seeing multiple events, that's strange. What MIDI device are you using?

> Was looking for some alternatives to https://github.com/djipco/webmidi with hooks support.

I initially created this repository to test the MIDIAccess API. However, I am thinking of maturing this package by utilizing the webmidi project which has covered more uses. Are you looking for hooks support or was there something lacking from that repository?

**Comment by ilionic** [comment]
> I wanted to know the "real" key that was pressed on the device.

Interesting requirement but not something I would expect from midi input library, as there are standard things ( ie 69 is A4 and 440hz ). Many libraries based on such standards if I need to feed an oscillator or play piano sample. Anyway, something I tried and adjusted by addition of 21 but felt weird.
MIDI device - NI Komplete 49. I compared with bunch of other libraries and other worked fine. So settled for now with https://github.com/nickroberts404/react-midi-hooks 
The reason switching from `webmidi` - just to have support for hooks since local state behaves strangely inside of event listeners.
Perhaps I could'v just write additional wrappers and custom hooks around webmidi but didn't have time / energy doing it.

**Comment by matthewshirley** [comment]
Thanks for the feedback and apologies for the duplicate event issue. I didn't realize that would be an unusual requirement but can remove the calculation of the position to avoid confusion. I would definitely recommend a more mature library since this has library has only had a few hours of work.
